# Sets up the services for running the project

version: '2.4'

networks:

  redis_bridge:
    internal: true
    driver: bridge

  sql_bridge:
    internal: true
    driver: bridge

services:

  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: sql
    environment:
      - PUID=1000
      - PGID=1000
      - FILE__MYSQL_ROOT_PASSWORD=./docker/secret_mysql_root_password
      - FILE__MYSQL_PASSWORD=./docker/secret_mysql_password
      - MYSQL_DATABASE=activities
      - MYSQL_USER=activities_user
      - TZ=Europe/Paris
    volumes:
      - ./docker/activities/sql/config:/config
    restart: unless-stopped
    networks:
      - sql_bridge

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./docker/activities/redis/config:/config
    restart: unless-stopped
    networks:
      - redis_bridge

  server:
    build: .
    container_name: server
    environment:
      - FLASK_APP=activities
      - FLASK_RUN_HOST=0.0.0.0
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - redis
      - mariadb
    networks:
      - redis_bridge
      - sql_bridge
