# Sets up the services for running the project

version: '2.4'

networks:
  db_bridge:
    internal: true
    driver: bridge

services:

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped
    networks:
      - db_bridge

  python:
    image: python:3.9
    container_name: python
    environment:
      - FLASK_APP=activities.py
      - FLASK_RUN_HOST=0.0.0.0
    restart: unless-stopped
    #command: bash -c "mkdir /app && cd /app && git clone git@github.com:LilianBoulard/activities.git && cd activities/ && pip install -r requirements.txt"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - redis
    networks:
      - db_bridge
