# Sets up the services for running the project

version: '2.4'

networks:

  redis_bridge:
    internal: true
    driver: bridge

  sql_bridge:
    internal: true
    driver: bridge

  # Remove if you don't use a reverse-proxy on docker
  reverse_proxy_net:
    external: true

services:

  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: activities_sql
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_DATABASE=activities
      - MYSQL_USER=activities_user
      - TZ=Europe/Paris
    volumes:
      - ./docker/live/sql/config:/config
    restart: unless-stopped
    env_file: docker/stack.env
    networks:
      - sql_bridge

  redis:
    build:
      context: .
      dockerfile: ./docker/redis_dockerfile
    container_name: activities_redis
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./docker/live/redis/data:/data
      - ./run_redis.sh:/data/run_redis.sh
    env_file: docker/stack.env
    restart: unless-stopped
    networks:
      - redis_bridge

  activities:
    build:
      context: .
      dockerfile: ./docker/activities_dockerfile
    container_name: activities
    env_file: docker/stack.env
    restart: unless-stopped
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    devices:
      - /dev/dri:/dev/dri
    #ports:
    #  - 8000:8000
    depends_on:
      - redis
      - mariadb
    networks:
      - redis_bridge
      - sql_bridge
      - default
      # Remove if you don't use a reverse-proxy on docker
      - reverse_proxy_net
