# Sets up the services for running the project

version: '2.4'

networks:

  redis_bridge:
    internal: true
    driver: bridge

  sql_bridge:
    internal: true
    driver: bridge

  # Remove if you don't use a reverse-proxy on docker
  reverse_proxy_net:
    external: true

services:

  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: sql
    environment:
      - PUID=1000
      - PGID=1000
      - FILE__MYSQL_ROOT_PASSWORD=./docker/secret_mysql_root_password
      - FILE__MYSQL_PASSWORD=./docker/secret_mysql_password
      - MYSQL_DATABASE=activities
      - MYSQL_USER=activities_user
      - TZ=Europe/Paris
    volumes:
      - ./docker/live/sql/config:/config
    restart: unless-stopped
    networks:
      - sql_bridge

  redis:
    build: ./docker/redis
    container_name: redis
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./docker/live/redis/data:/data
      - ./docker/redis/redis.conf:/etc/redis/redis.conf:ro
    restart: unless-stopped
    networks:
      - redis_bridge

  server:
    build: ./docker/activities
    container_name: server
    restart: unless-stopped
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8000:8000
    depends_on:
      - redis
      - mariadb
    networks:
      - redis_bridge
      - sql_bridge
      - default
      # Remove if you don't use a reverse-proxy on docker
      - reverse_proxy_net

  server_dev:
    build: ./docker/activities
    container_name: server_dev
    restart: unless-stopped
    runtime: nvidia
    environment:
      - FLASK_DEBUG=1
      - NVIDIA_VISIBLE_DEVICES=all
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - .:/usr/src/app
    ports:
      - 8001:8000
    depends_on:
      - redis
      - mariadb
    networks:
      - redis_bridge
      - sql_bridge
      - default